# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  #- "test"
  - "store"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "iacou/projects"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "api"
    working_directory: "${{clone}}/kubernetes/api/service"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  # test:
  #   title: "Running test"
  #   type: "freestyle" # Run any command
  #   image: "ubuntu:latest" # The image in which command will be executed
  #   working_directory: "${{clone}}" # Running command where code cloned
  #   commands:
  #     - "ls"
  #   stage: "test"
  
  storeChart:
    title: Storing Helm Chart
    type: helm
    stage: store
    working_directory: "${{clone}}/kubernetes"
    arguments:
      action: push
      helm_version: 3.2.3
      chart_name: "api/helm/charts"
      chart_repo_url: 'cm://h.cfcr.io/iacou.eu/default'

  deployChart:
    type: helm
    stage: deploy
    arguments:
      action: install
      helm_version: 3.2.3
      chart_name: "api"
      release_name: colourapi
      kube_context: iacou@colourapi
      custom_values:
        - 'image_tag=${{CF_SHORT_REVISION}}'
