apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "api.fullname" $ }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /pod
spec:
  rules:
  - http:
      paths:
      {{- range $colour := .Values.colours }}
      {{- if .ingressEnabled }}
      - path: "/deployment/{{ $colour.name }}"
        pathType: Exact
        backend:
          serviceName: {{ include "api.fullname" $ }}-{{ $colour.name }}
          servicePort: http
      {{- end }}
      {{- end }}
---
