# Default values for api.

replicaCount: 1

image:
  repo: localhost:5000
  pullPolicy: Always
  tag: latest

colours:
  - name: red
    ingressEnabled: true
  - name: green
    ingressEnabled: true
  - name: blue
    ingressEnabled: true

podAnnotations: {}

service:
  type: NodePort
  port: 80