apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "api.fullname" $ }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
spec:
  rules:
  - http:
      paths:
      {{- range $colour := .Values.colours }}
      {{- if .ingressEnabled }}
      - path: "/deployment/{{ $colour.name }}"
        backend:
          serviceName: {{ include "api.fullname" $ }}-{{ $colour.name }}
          servicePort: http
      {{- end }}
      {{- end }}
---
