---
- name: create file
  hosts: '*'
  tasks:
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
      access_time: preserve
      modification_time: preserve
